# Generated by Django 2.1.7 on 2019-03-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
