# Generated by Django 2.1.7 on 2019-03-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0002_bookinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
