# Generated by Django 2.1.7 on 2019-03-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0003_auto_20190325_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
