# Generated by Django 2.1.7 on 2019-03-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0006_auto_20190325_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop_Book_shop_dg_tmp',
            new_name='Shop',
        ),
    ]
