# Generated by Django 2.1.7 on 2019-03-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0007_auto_20190325_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='first_name',
            new_name='Adress',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='last_name',
            new_name='Name',
        ),
    ]
