# Generated by Django 2.1.7 on 2019-03-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0008_auto_20190325_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_Book.Book'),
        ),
    ]
