# Generated by Django 2.1.7 on 2019-03-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_Book', '0009_shop_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
